name: CI Pipeline

on:
  push:
    branches:
      - main
      - '**' # Trigger on any branch push
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements-dev.txt

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Black
        run: |
          python -m venv venv
          source venv/bin/activate
          black --check .

  security-scans:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Dependency Security Check (Safety)
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install safety
          safety check --full-report

      - name: Security Scan with Bandit
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install bandit
          bandit -r .

  tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Tests with Coverage
        run: |
          python -m venv venv
          source venv/bin/activate
          pytest --cov=. --cov-report=xml

  # upload-coverage:
  #   runs-on: ubuntu-latest
  #   needs: tests
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Upload Coverage to Codecov
  #       uses: codecov/codecov-action@v3
  #       with:
  #         files: ./coverage.xml
  #         flags: unittests       # Optional flag to identify the report
  #         name: CI Coverage      # Name of the coverage report
