name: CI Pipeline

on:
  push:
    branches:
      - main
      - '**' # Trigger on any branch push
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Step 4: Run Tests with Coverage
      - name: Run Tests with Coverage
        run: |
          source venv/bin/activate
          pytest --cov=. --cov-report=xml

      # Step 5: Upload Coverage to Codecov
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests       # Optional flag to identify the report
          name: CI Coverage      # Name of the coverage report
