name: CI Pipeline

on:
  push:
    branches:
      - main
      - '**' # Trigger on any branch push
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Cache Dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements-dev.txt
      # Step 5: Cache Virtual Environment (Optional)
      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: venv
          key: ${{ runner.os }}-venv

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Reuse Virtual Environment
        run: source venv/bin/activate
      - name: Run Black
        run: black --check .

  security-scans:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Reuse Virtual Environment
        run: source venv/bin/activate
      - name: Dependency Security Check (Safety)
        run: safety check --full-report
      - name: Security Scan with Bandit
        run: bandit -r .

  tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Reuse Virtual Environment
        run: source venv/bin/activate
      - name: Run Tests with Coverage
        run: pytest --cov=. --cov-report=xml

  # Uncomment this if you want to upload coverage to Codecov
  # upload-coverage:
  #   runs-on: ubuntu-latest
  #   needs: tests
  #   steps:
  #     - name: Upload Coverage to Codecov
  #       uses: codecov/codecov-action@v3
  #       with:
  #         files: ./coverage.xml
  #         flags: unittests
  #         name: CI Coverage
